version: '3'
services:
  database:
    container_name: "${SERVICE_NAME}-db-devel"
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
        - MYSQL_DATABASE=${MYSQL_DB}
    ports:
      - "3306:3306"
    networks: 
      - network-devel
    volumes: 
      - ../migrations/build:/docker-entrypoint-initdb.d/

networks:
  network-devel: